/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq;


import com.cj.jooq.jooq.tables.CustDeviceInfo;
import com.cj.jooq.jooq.tables.CustDevicePushLog;
import com.cj.jooq.jooq.tables.UPermission;
import com.cj.jooq.jooq.tables.URole;
import com.cj.jooq.jooq.tables.URolePermission;
import com.cj.jooq.jooq.tables.UUser;
import com.cj.jooq.jooq.tables.UUserRole;
import com.cj.jooq.jooq.tables.UserT;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUST_DEVICE_INFO_IDX_ID = Indexes0.CUST_DEVICE_INFO_IDX_ID;
    public static final Index CUST_DEVICE_INFO_IDX_PUSH_TOKEN = Indexes0.CUST_DEVICE_INFO_IDX_PUSH_TOKEN;
    public static final Index CUST_DEVICE_INFO_IDX_USERNAME = Indexes0.CUST_DEVICE_INFO_IDX_USERNAME;
    public static final Index CUST_DEVICE_INFO_PRIMARY = Indexes0.CUST_DEVICE_INFO_PRIMARY;
    public static final Index CUST_DEVICE_PUSH_LOG_IDX_ID = Indexes0.CUST_DEVICE_PUSH_LOG_IDX_ID;
    public static final Index CUST_DEVICE_PUSH_LOG_IDX_USERNAME = Indexes0.CUST_DEVICE_PUSH_LOG_IDX_USERNAME;
    public static final Index CUST_DEVICE_PUSH_LOG_PRIMARY = Indexes0.CUST_DEVICE_PUSH_LOG_PRIMARY;
    public static final Index USER_T_PRIMARY = Indexes0.USER_T_PRIMARY;
    public static final Index U_PERMISSION_PRIMARY = Indexes0.U_PERMISSION_PRIMARY;
    public static final Index U_ROLE_PRIMARY = Indexes0.U_ROLE_PRIMARY;
    public static final Index U_ROLE_PERMISSION_PRIMARY = Indexes0.U_ROLE_PERMISSION_PRIMARY;
    public static final Index U_USER_PRIMARY = Indexes0.U_USER_PRIMARY;
    public static final Index U_USER_ROLE_PRIMARY = Indexes0.U_USER_ROLE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index CUST_DEVICE_INFO_IDX_ID = createIndex("idx_id", CustDeviceInfo.CUST_DEVICE_INFO, new OrderField[] { CustDeviceInfo.CUST_DEVICE_INFO.ID }, true);
        public static Index CUST_DEVICE_INFO_IDX_PUSH_TOKEN = createIndex("idx_push_token", CustDeviceInfo.CUST_DEVICE_INFO, new OrderField[] { CustDeviceInfo.CUST_DEVICE_INFO.PUSH_TOKEN }, true);
        public static Index CUST_DEVICE_INFO_IDX_USERNAME = createIndex("idx_username", CustDeviceInfo.CUST_DEVICE_INFO, new OrderField[] { CustDeviceInfo.CUST_DEVICE_INFO.USERNAME }, false);
        public static Index CUST_DEVICE_INFO_PRIMARY = createIndex("PRIMARY", CustDeviceInfo.CUST_DEVICE_INFO, new OrderField[] { CustDeviceInfo.CUST_DEVICE_INFO.ID }, true);
        public static Index CUST_DEVICE_PUSH_LOG_IDX_ID = createIndex("idx_id", CustDevicePushLog.CUST_DEVICE_PUSH_LOG, new OrderField[] { CustDevicePushLog.CUST_DEVICE_PUSH_LOG.ID }, true);
        public static Index CUST_DEVICE_PUSH_LOG_IDX_USERNAME = createIndex("idx_username", CustDevicePushLog.CUST_DEVICE_PUSH_LOG, new OrderField[] { CustDevicePushLog.CUST_DEVICE_PUSH_LOG.USERNAME }, false);
        public static Index CUST_DEVICE_PUSH_LOG_PRIMARY = createIndex("PRIMARY", CustDevicePushLog.CUST_DEVICE_PUSH_LOG, new OrderField[] { CustDevicePushLog.CUST_DEVICE_PUSH_LOG.ID }, true);
        public static Index USER_T_PRIMARY = createIndex("PRIMARY", UserT.USER_T, new OrderField[] { UserT.USER_T.ID }, true);
        public static Index U_PERMISSION_PRIMARY = createIndex("PRIMARY", UPermission.U_PERMISSION, new OrderField[] { UPermission.U_PERMISSION.ID }, true);
        public static Index U_ROLE_PRIMARY = createIndex("PRIMARY", URole.U_ROLE, new OrderField[] { URole.U_ROLE.ID }, true);
        public static Index U_ROLE_PERMISSION_PRIMARY = createIndex("PRIMARY", URolePermission.U_ROLE_PERMISSION, new OrderField[] { URolePermission.U_ROLE_PERMISSION.ID }, true);
        public static Index U_USER_PRIMARY = createIndex("PRIMARY", UUser.U_USER, new OrderField[] { UUser.U_USER.ID }, true);
        public static Index U_USER_ROLE_PRIMARY = createIndex("PRIMARY", UUserRole.U_USER_ROLE, new OrderField[] { UUserRole.U_USER_ROLE.ID }, true);
    }
}
