/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq;


import com.cj.jooq.jooq.tables.CustDeviceInfo;
import com.cj.jooq.jooq.tables.CustDevicePushLog;
import com.cj.jooq.jooq.tables.UPermission;
import com.cj.jooq.jooq.tables.URole;
import com.cj.jooq.jooq.tables.URolePermission;
import com.cj.jooq.jooq.tables.UUser;
import com.cj.jooq.jooq.tables.UUserRole;
import com.cj.jooq.jooq.tables.UserT;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 客户设备信息表
     */
    public static final CustDeviceInfo CUST_DEVICE_INFO = com.cj.jooq.jooq.tables.CustDeviceInfo.CUST_DEVICE_INFO;

    /**
     * 设备推送日志表
     */
    public static final CustDevicePushLog CUST_DEVICE_PUSH_LOG = com.cj.jooq.jooq.tables.CustDevicePushLog.CUST_DEVICE_PUSH_LOG;

    /**
     * The table <code>test.user_t</code>.
     */
    public static final UserT USER_T = com.cj.jooq.jooq.tables.UserT.USER_T;

    /**
     * The table <code>test.u_permission</code>.
     */
    public static final UPermission U_PERMISSION = com.cj.jooq.jooq.tables.UPermission.U_PERMISSION;

    /**
     * The table <code>test.u_role</code>.
     */
    public static final URole U_ROLE = com.cj.jooq.jooq.tables.URole.U_ROLE;

    /**
     * The table <code>test.u_role_permission</code>.
     */
    public static final URolePermission U_ROLE_PERMISSION = com.cj.jooq.jooq.tables.URolePermission.U_ROLE_PERMISSION;

    /**
     * The table <code>test.u_user</code>.
     */
    public static final UUser U_USER = com.cj.jooq.jooq.tables.UUser.U_USER;

    /**
     * The table <code>test.u_user_role</code>.
     */
    public static final UUserRole U_USER_ROLE = com.cj.jooq.jooq.tables.UUserRole.U_USER_ROLE;
}
