/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables;


import com.cj.jooq.jooq.Indexes;
import com.cj.jooq.jooq.Keys;
import com.cj.jooq.jooq.Test;
import com.cj.jooq.jooq.tables.records.CustDeviceInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 客户设备信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustDeviceInfo extends TableImpl<CustDeviceInfoRecord> {

    private static final long serialVersionUID = -527523004;

    /**
     * The reference instance of <code>test.cust_device_info</code>
     */
    public static final CustDeviceInfo CUST_DEVICE_INFO = new CustDeviceInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustDeviceInfoRecord> getRecordType() {
        return CustDeviceInfoRecord.class;
    }

    /**
     * The column <code>test.cust_device_info.ID</code>.
     */
    public final TableField<CustDeviceInfoRecord, Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>test.cust_device_info.CREATE_TIME</code>.
     */
    public final TableField<CustDeviceInfoRecord, LocalDateTime> CREATE_TIME = createField("CREATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>test.cust_device_info.CREATE_BY</code>. 创建人用户名  
     */
    public final TableField<CustDeviceInfoRecord, String> CREATE_BY = createField("CREATE_BY", org.jooq.impl.SQLDataType.VARCHAR(20), this, "创建人用户名  ");

    /**
     * The column <code>test.cust_device_info.UPDATE_TIME</code>.
     */
    public final TableField<CustDeviceInfoRecord, LocalDateTime> UPDATE_TIME = createField("UPDATE_TIME", org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>test.cust_device_info.UPDATE_BY</code>. 修改人用户名
     */
    public final TableField<CustDeviceInfoRecord, String> UPDATE_BY = createField("UPDATE_BY", org.jooq.impl.SQLDataType.VARCHAR(20), this, "修改人用户名");

    /**
     * The column <code>test.cust_device_info.USERNAME</code>. 用户名
     */
    public final TableField<CustDeviceInfoRecord, String> USERNAME = createField("USERNAME", org.jooq.impl.SQLDataType.VARCHAR(20), this, "用户名");

    /**
     * The column <code>test.cust_device_info.TERMINAL_ID</code>. 设备唯一码
     */
    public final TableField<CustDeviceInfoRecord, String> TERMINAL_ID = createField("TERMINAL_ID", org.jooq.impl.SQLDataType.VARCHAR(40), this, "设备唯一码");

    /**
     * The column <code>test.cust_device_info.PUSH_TOKEN</code>. 推送平台下发的设备唯一码
     */
    public final TableField<CustDeviceInfoRecord, String> PUSH_TOKEN = createField("PUSH_TOKEN", org.jooq.impl.SQLDataType.VARCHAR(64), this, "推送平台下发的设备唯一码");

    /**
     * The column <code>test.cust_device_info.OS_VERSION</code>. 原生系统版本
     */
    public final TableField<CustDeviceInfoRecord, String> OS_VERSION = createField("OS_VERSION", org.jooq.impl.SQLDataType.VARCHAR(30), this, "原生系统版本");

    /**
     * The column <code>test.cust_device_info.BUNDLE_VERSION</code>. 客户端当前版本号，例如：1.0.1
     */
    public final TableField<CustDeviceInfoRecord, String> BUNDLE_VERSION = createField("BUNDLE_VERSION", org.jooq.impl.SQLDataType.VARCHAR(30), this, "客户端当前版本号，例如：1.0.1");

    /**
     * The column <code>test.cust_device_info.FACTORY_OS_VERSION</code>. 手机厂商自定义OS，只对Android device有效)
     */
    public final TableField<CustDeviceInfoRecord, String> FACTORY_OS_VERSION = createField("FACTORY_OS_VERSION", org.jooq.impl.SQLDataType.VARCHAR(30), this, "手机厂商自定义OS，只对Android device有效)");

    /**
     * The column <code>test.cust_device_info.DEVICE_MODEL</code>. 手机型号
     */
    public final TableField<CustDeviceInfoRecord, String> DEVICE_MODEL = createField("DEVICE_MODEL", org.jooq.impl.SQLDataType.VARCHAR(30), this, "手机型号");

    /**
     * The column <code>test.cust_device_info.DEVICE_TYPE</code>. 设备类型. 1:安卓  2:ios
     */
    public final TableField<CustDeviceInfoRecord, String> DEVICE_TYPE = createField("DEVICE_TYPE", org.jooq.impl.SQLDataType.VARCHAR(10), this, "设备类型. 1:安卓  2:ios");

    /**
     * Create a <code>test.cust_device_info</code> table reference
     */
    public CustDeviceInfo() {
        this(DSL.name("cust_device_info"), null);
    }

    /**
     * Create an aliased <code>test.cust_device_info</code> table reference
     */
    public CustDeviceInfo(String alias) {
        this(DSL.name(alias), CUST_DEVICE_INFO);
    }

    /**
     * Create an aliased <code>test.cust_device_info</code> table reference
     */
    public CustDeviceInfo(Name alias) {
        this(alias, CUST_DEVICE_INFO);
    }

    private CustDeviceInfo(Name alias, Table<CustDeviceInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CustDeviceInfo(Name alias, Table<CustDeviceInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "客户设备信息表");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CUST_DEVICE_INFO_IDX_ID, Indexes.CUST_DEVICE_INFO_IDX_PUSH_TOKEN, Indexes.CUST_DEVICE_INFO_IDX_USERNAME, Indexes.CUST_DEVICE_INFO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CustDeviceInfoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CUST_DEVICE_INFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CustDeviceInfoRecord> getPrimaryKey() {
        return Keys.KEY_CUST_DEVICE_INFO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CustDeviceInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<CustDeviceInfoRecord>>asList(Keys.KEY_CUST_DEVICE_INFO_PRIMARY, Keys.KEY_CUST_DEVICE_INFO_IDX_ID, Keys.KEY_CUST_DEVICE_INFO_IDX_PUSH_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfo as(String alias) {
        return new CustDeviceInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfo as(Name alias) {
        return new CustDeviceInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustDeviceInfo rename(String name) {
        return new CustDeviceInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustDeviceInfo rename(Name name) {
        return new CustDeviceInfo(name, null);
    }
}
