/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables;


import com.cj.jooq.jooq.Indexes;
import com.cj.jooq.jooq.Keys;
import com.cj.jooq.jooq.Test;
import com.cj.jooq.jooq.tables.records.URolePermissionRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class URolePermission extends TableImpl<URolePermissionRecord> {

    private static final long serialVersionUID = -1486892022;

    /**
     * The reference instance of <code>test.u_role_permission</code>
     */
    public static final URolePermission U_ROLE_PERMISSION = new URolePermission();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<URolePermissionRecord> getRecordType() {
        return URolePermissionRecord.class;
    }

    /**
     * The column <code>test.u_role_permission.id</code>.
     */
    public final TableField<URolePermissionRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>test.u_role_permission.rid</code>. 角色ID
     */
    public final TableField<URolePermissionRecord, String> RID = createField("rid", org.jooq.impl.SQLDataType.VARCHAR(32), this, "角色ID");

    /**
     * The column <code>test.u_role_permission.pid</code>. 权限ID
     */
    public final TableField<URolePermissionRecord, String> PID = createField("pid", org.jooq.impl.SQLDataType.VARCHAR(32), this, "权限ID");

    /**
     * Create a <code>test.u_role_permission</code> table reference
     */
    public URolePermission() {
        this(DSL.name("u_role_permission"), null);
    }

    /**
     * Create an aliased <code>test.u_role_permission</code> table reference
     */
    public URolePermission(String alias) {
        this(DSL.name(alias), U_ROLE_PERMISSION);
    }

    /**
     * Create an aliased <code>test.u_role_permission</code> table reference
     */
    public URolePermission(Name alias) {
        this(alias, U_ROLE_PERMISSION);
    }

    private URolePermission(Name alias, Table<URolePermissionRecord> aliased) {
        this(alias, aliased, null);
    }

    private URolePermission(Name alias, Table<URolePermissionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Test.TEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.U_ROLE_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<URolePermissionRecord> getPrimaryKey() {
        return Keys.KEY_U_ROLE_PERMISSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<URolePermissionRecord>> getKeys() {
        return Arrays.<UniqueKey<URolePermissionRecord>>asList(Keys.KEY_U_ROLE_PERMISSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public URolePermission as(String alias) {
        return new URolePermission(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public URolePermission as(Name alias) {
        return new URolePermission(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public URolePermission rename(String name) {
        return new URolePermission(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public URolePermission rename(Name name) {
        return new URolePermission(name, null);
    }
}
