/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 客户设备信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustDeviceInfo implements Serializable {

    private static final long serialVersionUID = -524733486;

    private Integer       id;
    private LocalDateTime createTime;
    private String        createBy;
    private LocalDateTime updateTime;
    private String        updateBy;
    private String        username;
    private String        terminalId;
    private String        pushToken;
    private String        osVersion;
    private String        bundleVersion;
    private String        factoryOsVersion;
    private String        deviceModel;
    private String        deviceType;

    public CustDeviceInfo() {}

    public CustDeviceInfo(CustDeviceInfo value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.createBy = value.createBy;
        this.updateTime = value.updateTime;
        this.updateBy = value.updateBy;
        this.username = value.username;
        this.terminalId = value.terminalId;
        this.pushToken = value.pushToken;
        this.osVersion = value.osVersion;
        this.bundleVersion = value.bundleVersion;
        this.factoryOsVersion = value.factoryOsVersion;
        this.deviceModel = value.deviceModel;
        this.deviceType = value.deviceType;
    }

    public CustDeviceInfo(
        Integer       id,
        LocalDateTime createTime,
        String        createBy,
        LocalDateTime updateTime,
        String        updateBy,
        String        username,
        String        terminalId,
        String        pushToken,
        String        osVersion,
        String        bundleVersion,
        String        factoryOsVersion,
        String        deviceModel,
        String        deviceType
    ) {
        this.id = id;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
        this.username = username;
        this.terminalId = terminalId;
        this.pushToken = pushToken;
        this.osVersion = osVersion;
        this.bundleVersion = bundleVersion;
        this.factoryOsVersion = factoryOsVersion;
        this.deviceModel = deviceModel;
        this.deviceType = deviceType;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTerminalId() {
        return this.terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public String getPushToken() {
        return this.pushToken;
    }

    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    public String getOsVersion() {
        return this.osVersion;
    }

    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion;
    }

    public String getBundleVersion() {
        return this.bundleVersion;
    }

    public void setBundleVersion(String bundleVersion) {
        this.bundleVersion = bundleVersion;
    }

    public String getFactoryOsVersion() {
        return this.factoryOsVersion;
    }

    public void setFactoryOsVersion(String factoryOsVersion) {
        this.factoryOsVersion = factoryOsVersion;
    }

    public String getDeviceModel() {
        return this.deviceModel;
    }

    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
    }

    public String getDeviceType() {
        return this.deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustDeviceInfo (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(username);
        sb.append(", ").append(terminalId);
        sb.append(", ").append(pushToken);
        sb.append(", ").append(osVersion);
        sb.append(", ").append(bundleVersion);
        sb.append(", ").append(factoryOsVersion);
        sb.append(", ").append(deviceModel);
        sb.append(", ").append(deviceType);

        sb.append(")");
        return sb.toString();
    }
}
