/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * 设备推送日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustDevicePushLog implements Serializable {

    private static final long serialVersionUID = 674515027;

    private Integer       id;
    private LocalDateTime createTime;
    private String        createBy;
    private LocalDateTime updateTime;
    private LocalDateTime updateBy;
    private String        username;
    private String        terminalId;
    private String        pushToken;
    private String        deviceType;
    private Integer       seq;
    private String        environment;
    private Integer       retCode;
    private String        pushId;
    private String        message;

    public CustDevicePushLog() {}

    public CustDevicePushLog(CustDevicePushLog value) {
        this.id = value.id;
        this.createTime = value.createTime;
        this.createBy = value.createBy;
        this.updateTime = value.updateTime;
        this.updateBy = value.updateBy;
        this.username = value.username;
        this.terminalId = value.terminalId;
        this.pushToken = value.pushToken;
        this.deviceType = value.deviceType;
        this.seq = value.seq;
        this.environment = value.environment;
        this.retCode = value.retCode;
        this.pushId = value.pushId;
        this.message = value.message;
    }

    public CustDevicePushLog(
        Integer       id,
        LocalDateTime createTime,
        String        createBy,
        LocalDateTime updateTime,
        LocalDateTime updateBy,
        String        username,
        String        terminalId,
        String        pushToken,
        String        deviceType,
        Integer       seq,
        String        environment,
        Integer       retCode,
        String        pushId,
        String        message
    ) {
        this.id = id;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
        this.username = username;
        this.terminalId = terminalId;
        this.pushToken = pushToken;
        this.deviceType = deviceType;
        this.seq = seq;
        this.environment = environment;
        this.retCode = retCode;
        this.pushId = pushId;
        this.message = message;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public LocalDateTime getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(LocalDateTime updateBy) {
        this.updateBy = updateBy;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTerminalId() {
        return this.terminalId;
    }

    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    public String getPushToken() {
        return this.pushToken;
    }

    public void setPushToken(String pushToken) {
        this.pushToken = pushToken;
    }

    public String getDeviceType() {
        return this.deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public Integer getSeq() {
        return this.seq;
    }

    public void setSeq(Integer seq) {
        this.seq = seq;
    }

    public String getEnvironment() {
        return this.environment;
    }

    public void setEnvironment(String environment) {
        this.environment = environment;
    }

    public Integer getRetCode() {
        return this.retCode;
    }

    public void setRetCode(Integer retCode) {
        this.retCode = retCode;
    }

    public String getPushId() {
        return this.pushId;
    }

    public void setPushId(String pushId) {
        this.pushId = pushId;
    }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustDevicePushLog (");

        sb.append(id);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateBy);
        sb.append(", ").append(username);
        sb.append(", ").append(terminalId);
        sb.append(", ").append(pushToken);
        sb.append(", ").append(deviceType);
        sb.append(", ").append(seq);
        sb.append(", ").append(environment);
        sb.append(", ").append(retCode);
        sb.append(", ").append(pushId);
        sb.append(", ").append(message);

        sb.append(")");
        return sb.toString();
    }
}
