/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UPermission implements Serializable {

    private static final long serialVersionUID = 422698627;

    private String id;
    private String url;
    private String name;
    private String permission;
    private String parentid;
    private String parentids;

    public UPermission() {}

    public UPermission(UPermission value) {
        this.id = value.id;
        this.url = value.url;
        this.name = value.name;
        this.permission = value.permission;
        this.parentid = value.parentid;
        this.parentids = value.parentids;
    }

    public UPermission(
        String id,
        String url,
        String name,
        String permission,
        String parentid,
        String parentids
    ) {
        this.id = id;
        this.url = url;
        this.name = name;
        this.permission = permission;
        this.parentid = parentid;
        this.parentids = parentids;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPermission() {
        return this.permission;
    }

    public void setPermission(String permission) {
        this.permission = permission;
    }

    public String getParentid() {
        return this.parentid;
    }

    public void setParentid(String parentid) {
        this.parentid = parentid;
    }

    public String getParentids() {
        return this.parentids;
    }

    public void setParentids(String parentids) {
        this.parentids = parentids;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UPermission (");

        sb.append(id);
        sb.append(", ").append(url);
        sb.append(", ").append(name);
        sb.append(", ").append(permission);
        sb.append(", ").append(parentid);
        sb.append(", ").append(parentids);

        sb.append(")");
        return sb.toString();
    }
}
