/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserT implements Serializable {

    private static final long serialVersionUID = 541245795;

    private Integer id;
    private String  userName;
    private String  password;
    private Integer age;

    public UserT() {}

    public UserT(UserT value) {
        this.id = value.id;
        this.userName = value.userName;
        this.password = value.password;
        this.age = value.age;
    }

    public UserT(
        Integer id,
        String  userName,
        String  password,
        Integer age
    ) {
        this.id = id;
        this.userName = userName;
        this.password = password;
        this.age = age;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserT (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(password);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
