/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UUserRole implements Serializable {

    private static final long serialVersionUID = -1629453364;

    private String id;
    private String uid;
    private String rid;

    public UUserRole() {}

    public UUserRole(UUserRole value) {
        this.id = value.id;
        this.uid = value.uid;
        this.rid = value.rid;
    }

    public UUserRole(
        String id,
        String uid,
        String rid
    ) {
        this.id = id;
        this.uid = uid;
        this.rid = rid;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUid() {
        return this.uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getRid() {
        return this.rid;
    }

    public void setRid(String rid) {
        this.rid = rid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UUserRole (");

        sb.append(id);
        sb.append(", ").append(uid);
        sb.append(", ").append(rid);

        sb.append(")");
        return sb.toString();
    }
}
