/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UUser implements Serializable {

    private static final long serialVersionUID = -800808761;

    private String        id;
    private String        username;
    private String        realname;
    private String        email;
    private String        password;
    private LocalDateTime lastLoginTime;
    private Long          status;
    private String        salt;
    private Integer       age;
    private LocalDateTime createTime;
    private String        createBy;
    private LocalDateTime updateTime;
    private String        updateBy;

    public UUser() {}

    public UUser(UUser value) {
        this.id = value.id;
        this.username = value.username;
        this.realname = value.realname;
        this.email = value.email;
        this.password = value.password;
        this.lastLoginTime = value.lastLoginTime;
        this.status = value.status;
        this.salt = value.salt;
        this.age = value.age;
        this.createTime = value.createTime;
        this.createBy = value.createBy;
        this.updateTime = value.updateTime;
        this.updateBy = value.updateBy;
    }

    public UUser(
        String        id,
        String        username,
        String        realname,
        String        email,
        String        password,
        LocalDateTime lastLoginTime,
        Long          status,
        String        salt,
        Integer       age,
        LocalDateTime createTime,
        String        createBy,
        LocalDateTime updateTime,
        String        updateBy
    ) {
        this.id = id;
        this.username = username;
        this.realname = realname;
        this.email = email;
        this.password = password;
        this.lastLoginTime = lastLoginTime;
        this.status = status;
        this.salt = salt;
        this.age = age;
        this.createTime = createTime;
        this.createBy = createBy;
        this.updateTime = updateTime;
        this.updateBy = updateBy;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getRealname() {
        return this.realname;
    }

    public void setRealname(String realname) {
        this.realname = realname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public LocalDateTime getLastLoginTime() {
        return this.lastLoginTime;
    }

    public void setLastLoginTime(LocalDateTime lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public String getCreateBy() {
        return this.createBy;
    }

    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    public String getUpdateBy() {
        return this.updateBy;
    }

    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UUser (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(realname);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(lastLoginTime);
        sb.append(", ").append(status);
        sb.append(", ").append(salt);
        sb.append(", ").append(age);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createBy);
        sb.append(", ").append(updateTime);
        sb.append(", ").append(updateBy);

        sb.append(")");
        return sb.toString();
    }
}
