package com.cj.spring.exceptionHandler.enums;

public enum ResultEnum {

    //Result should be the same to persist in table T_CHECK_JOURNAL
    SUCCESS(1),
    FAILURE(0),
    RETRY(-1),
    PENDING(-9),
    TIMEOUT(-2),
    RESEND_SMS(-3),
    REDO_STEP(-4),


    APPLICATION_NOT_FOUND(40000),
    USER_ID_EMPTY(40001),
    EMPLOYEE_EMPTY(40002),
    BANK_CARD_UPDATE_FAILED(40011),
    ADDRESS_INSERT_FAILED(40012),
    BORROWER_UPDATE_FAILED(40013),
    EMPLOYER_UPDATE_FAILED(40014),
    FAMILY_MEMBER_INSERT_FAILED(40015),
    SA_OPINION_INSERT_FAILED(40016),
    CONTACTS_INSERT_FAILED(40017),
    OFFLINE_FACE_RECOGNITION_FAILED(40018),
    GOODS_UPDATE_FAILED(40019),
    APPLICATION_QUERY_FAILED(40020),
    SA_PASSWORD_VERIFICATION_FAILED(40021),
    PHOTO_SERVICE_QUERY_FAILED(40022),
    PHOTO_SERVICE_SAVE_CABINET_FAILED(40023),
    BAIDU_SERVICE_FAILED(40024),
    APPLICATION_ROW_LOCK_FAILED(40031),
    ///////////////////////////////////////////////////////////////////////

    //////////////////////////IDCARD GENERAL//////////////////////////////////////////////
    IDCARD_SAVE_FAILED(10001),
    IDCARD_SAVE_BORROWER_FAILED(10002),
    IDCARD_SAVE_APPLICATION_FAILED(10003),
    IDCARD_SAVE_IDCARD_ORC_FAILED(10004),
    IDCARD_ELIGIBILITY_CHECK_FAILED(10005),
    IDCARD_DATA_MISSMATCH(10006),
    //////////////////////////IDCARD GENERAL END///////////////////////////////////////////////

    /////////////////////////BANK CARD GENERAL///////////////////////////////////
    BANK_CARD_SAVE_DD_VENDOR_FAILED(20001),
    BANK_CARD_SAVE_BANK_CARD_FAILED(20002),
    BANK_CARD_SAVE_BANK_CARD_OCR_FAILED(20003),
    BANK_CARD_UPDATE_BANK_CARD_OCR_FAILED(20004),
    BANK_CARD_SAVE_BORROWER_FAILED(20005),
    BANK_CARD_DD_AUTH_CHECK_FAILED(20006),
    BANK_CARD_APPLICATION_STATUS_NOT_EXISTS(20007),
    BANK_CARD_UPDATE_APPLICATION_STATUS_FAILED(20008),


    /////////////////////////BANK CARD GENERAL END///////////////////////////////

    /////////////////////////AL GENERAL///////////////////////////////////
    AL_OTP_CHECK_FAILED(21001),
    AL_GET_ID_CARD_FAILED(21002),
    AL_GET_CIF_ID_FAILED(21003),
    AL_CREATE_CUSTOMER_FAILED(21004),
    AL_GET_ID_CART_FAILED(21005),
    AL_UPDATE_APPLICATION_STATUS_FAILED(21006),
    AL_UPDATE_APPLICATION_CDS_SIGNED_FAILED(21007),


    /////////////////////////AL GENERAL END///////////////////////////////

    /////////////////////////SMS GENERAL///////////////////////////////////
    SMS_GENERAL_UNKNOWN_ERROR(30001),
    SMS_GENERAL_ILLEGAL_VERIFICATION_TYPE(30002),
    SMS_GENERAL_INTERNAL_SERVER_ERROR(30003),
    SMS_GENERAL_BAD_REQUEST_ERROR(30004),
    SMS_GENERAL_UNAUTHORIZED_REQUEST_ERROR(30005),
    SMS_GENERAL_FORBIDDEN_ERROR(30006),
    SMS_GENERAL_NOT_FOUND_ERROR(30007),
    SMS_GENERAL_SMS_VERIFICATION_CODE_IS_EMPTY(30008),
    SMS_GENERAL_SMS_PARAMETER_INVALID(30009),

    /////////////////////////SMS GENERAL END///////////////////////////////

    /////////////////////////SMS DD AUTH///////////////////////////////////
    SMS_DD_AUTH_GENERATE_PROCESS_ID_FAIL(30021),
    SMS_DD_AUTH_GET_VENDOR_FAIL(30022),
    SMS_DD_AUTH_INVALID_CARDHOLDER_INFORMATION(30023),
    SMS_DD_AUTH_BANK_IS_NOT_SUPPORTED_BY_THIS_VENDOR(30024),
    SMS_DD_AUTH_BANK_CARD_EXPIRED_INVALID(30025),
    SMS_DD_AUTH_PAYMENT_CHANNEL_SYSTEM_ERROR(30026),
    SMS_DD_AUTH_NO_RESPONSE_FROM_VENDOR(30027),
    SMS_DD_AUTH_SMS_VERIFICATION_CODE_EXPIRED(30028),
    SMS_DD_AUTH_SMS_DATA_MISMATCHED(30029),
    SMS_DD_AUTH_INVALID_SMS_VERIFICATION_CODE(30030),
    /////////////////////////SMS DD AUTH END///////////////////////////////

    /////////////////////////SMS OTP///////////////////////////////////
    SMS_OTP_INVALID_TEMPLATE_ID(30041),
    SMS_OTP_VERIFICATION_MAX_VERIFY_ATTEMPTS_EXCEEDED(30042),
    SMS_OTP_VERIFICATION_FAILED(30043),
    SMS_OTP_VERIFICATION_SMS_CODE_NOT_VALID(30044),
    SMS_OTP_VERIFICATION_WRONG_SMS_CODE(30045),
    SMS_OTP_VERIFICATION_WRONG_AUTHORIZATION_ID(30046),
    SMS_OTP_REQUEST_FAILED(30047),
    SMS_OTP_REQUEST_MAX_ACTIVE_PASSWORDS_EXCEEDED(30048),
    SMS_OTP_REQUEST_SMS_GW_CONNECTION_FAILED(30049),
    SMS_OTP_REQUEST_SMS_GW_PARAMETER_ERROR(30050),
    SMS_OTP_REQUEST_SMS_GW_BATCH_PARTIAL_ERROR(30051),
    SMS_OTP_REQUEST_SMS_GW_UNKNOWN_STATUS(30052),
    SMS_OTP_REQUEST_KEY_GENERATION_FAILED(30053),
    SMS_OTP_REQUEST_UNKNOWN_OPERATION_TYPE(30054),
    SMS_OTP_REQUEST_WRONG_TEMPLATE_ID(30055),
    /////////////////////////SMS OTP END///////////////////////////////////

    /////////////////////////SMS HOMER GW /////////////////////////////////
    SMS_HOMER_GW_REQUEST_NO_BRANCH_ASSIGNED(30061),
    SMS_HOMER_GW_REQUEST_MISSING_ATTACHMENTS(30062),
    SMS_HOMER_GW_REQUEST_NOT_EXISTS_RIGHTS(30063),
    SMS_HOMER_GW_REQUEST_CONTRACT_NOT_FOUND(30064),
    SMS_HOMER_GW_REQUEST_WRONG_STATUS(30065),
    SMS_HOMER_GW_REQUEST_NOT_OWNER_BY_USER(30066),
    SMS_HOMER_GW_REQUEST_ALREADY_REGISTERED(30067),
    SMS_HOMER_GW_REQUEST_WRONG_QM(30068),
    SMS_HOMER_GW_REQUEST_CONTRACT_IS_PAPERLESS(30069),
    SMS_HOMER_GW_REQUEST_MISSING_IMEI(30070),
    SMS_HOMER_GW_REQUEST_MISSING_PRINTS(30071),
    SMS_HOMER_GW_REQUEST_INSUFFICIENT_PRIVILEGES(30072),
    SMS_HOMER_GW_REQUEST_VIN_IS_MISSING(30073),
    SMS_HOMER_GW_REQUEST_ACQUISITION_CHANNEL_SMARTPOS(30074),
    SMS_HOMER_GW_REQUEST_CONTRACT_DOES_NOT_MATCH_CRITERIA(30075),
    SMS_HOMER_GW_REQUEST_OPR_MOBILE_MISSING(30076),
    SMS_HOMER_GW_REQUEST_MANDATORY_DOCUMENTS_MISSING(30077),

    SMS_HOMER_GW_VERIFICATION_OK_AND_OK(60000),
    SMS_HOMER_GW_VERIFICATION_OK_AND_FAILED(60001),
    SMS_HOMER_GW_VERIFICATION_OK_AND_FAILED_CONTRACT_CANCEL(60002),
    SMS_HOMER_GW_VERIFICATION_OK_AND_NO_DATA_FOUND(60003),
    SMS_HOMER_GW_VERIFICATION_OK_AND_TIMEOUT(60004),
    SMS_HOMER_GW_VERIFICATION_OK_AND_FAILED_CONTRACT_NOT_CANCEL(60005),
    SMS_HOMER_GW_VERIFICATION_OK_AND_FAILED_CONTRACT_NOT_REGISTER(60006),
    SMS_HOMER_GW_VERIFICATION_OK_AND_DATA_NOT_AUTHORIZED(60007),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_OK(60100),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_FAILED(60101),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_FAILED_CONTRACT_CANCEL(60102),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_NO_DATA_FOUND(60103),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_TIMEOUT(60104),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_FAILED_CONTRACT_NOT_CANCEL(60105),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_FAILED_CONTRACT_NOT_REGISTER(60106),
    SMS_HOMER_GW_VERIFICATION_NO_BRANCH_ASSIGNED_AND_DATA_NOT_AUTHORIZED(60107),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_OK(60200),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_FAILED(60201),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_FAILED_CONTRACT_CANCEL(60202),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_NO_DATA_FOUND(60203),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_TIMEOUT(60204),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_FAILED_CONTRACT_NOT_CANCEL(60205),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_FAILED_CONTRACT_NOT_REGISTER(60206),
    SMS_HOMER_GW_VERIFICATION_MISSING_ATTACHMENTS_AND_DATA_NOT_AUTHORIZED(60207),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_OK(60300),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_FAILED(60301),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_FAILED_CONTRACT_CANCEL(60302),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_NO_DATA_FOUND(60303),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_TIMEOUT(60304),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_FAILED_CONTRACT_NOT_CANCEL(60305),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_FAILED_CONTRACT_NOT_REGISTER(60306),
    SMS_HOMER_GW_VERIFICATION_NOT_EXISTS_RIGHTS_AND_DATA_NOT_AUTHORIZED(60307),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_OK(60400),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_FAILED(60401),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_FAILED_CONTRACT_CANCEL(60402),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_NO_DATA_FOUND(60403),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_TIMEOUT(60404),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_FAILED_CONTRACT_NOT_CANCEL(60405),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_FAILED_CONTRACT_NOT_REGISTER(60406),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_NOT_FOUND_AND_DATA_NOT_AUTHORIZED(60407),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_OK(60500),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_FAILED(60501),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_FAILED_CONTRACT_CANCEL(60502),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_NO_DATA_FOUND(60503),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_TIMEOUT(60504),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_FAILED_CONTRACT_NOT_CANCEL(60505),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_FAILED_CONTRACT_NOT_REGISTER(60506),
    SMS_HOMER_GW_VERIFICATION_WRONG_STATUS_AND_DATA_NOT_AUTHORIZED(60507),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_OK(60600),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_FAILED(60601),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_FAILED_CONTRACT_CANCEL(60602),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_NO_DATA_FOUND(60603),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_TIMEOUT(60604),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_FAILED_CONTRACT_NOT_CANCEL(60605),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_FAILED_CONTRACT_NOT_REGISTER(60606),
    SMS_HOMER_GW_VERIFICATION_NOT_OWNER_BY_USER_AND_DATA_NOT_AUTHORIZED(60607),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_OK(60700),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_FAILED(60701),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_FAILED_CONTRACT_CANCEL(60702),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_NO_DATA_FOUND(60703),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_TIMEOUT(60704),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_FAILED_CONTRACT_NOT_CANCEL(60705),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_FAILED_CONTRACT_NOT_REGISTER(60706),
    SMS_HOMER_GW_VERIFICATION_ALREADY_REGISTERED_AND_DATA_NOT_AUTHORIZED(60707),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_OK(60800),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_FAILED(60801),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_FAILED_CONTRACT_CANCEL(60802),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_NO_DATA_FOUND(60803),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_TIMEOUT(60804),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_FAILED_CONTRACT_NOT_CANCEL(60805),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_FAILED_CONTRACT_NOT_REGISTER(60806),
    SMS_HOMER_GW_VERIFICATION_WRONG_QM_AND_DATA_NOT_AUTHORIZED(60807),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_OK(60900),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_FAILED(60901),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_FAILED_CONTRACT_CANCEL(60902),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_NO_DATA_FOUND(60903),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_TIMEOUT(60904),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_FAILED_CONTRACT_NOT_CANCEL(60905),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_FAILED_CONTRACT_NOT_REGISTER(60906),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_IS_PAPERLESS_AND_DATA_NOT_AUTHORIZED(60907),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_OK(61000),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_FAILED(61001),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_FAILED_CONTRACT_CANCEL(61002),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_NO_DATA_FOUND(61003),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_TIMEOUT(61004),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_FAILED_CONTRACT_NOT_CANCEL(61005),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_FAILED_CONTRACT_NOT_REGISTER(61006),
    SMS_HOMER_GW_VERIFICATION_MISSING_IMEI_AND_DATA_NOT_AUTHORIZED(61007),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_OK(61100),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_FAILED(61101),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_FAILED_CONTRACT_CANCEL(61102),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_NO_DATA_FOUND(61103),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_TIMEOUT(61104),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_FAILED_CONTRACT_NOT_CANCEL(61105),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_FAILED_CONTRACT_NOT_REGISTER(61106),
    SMS_HOMER_GW_VERIFICATION_MISSING_PRINTS_AND_DATA_NOT_AUTHORIZED(61107),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_OK(61200),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_FAILED(61201),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_FAILED_CONTRACT_CANCEL(61202),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_NO_DATA_FOUND(61203),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_TIMEOUT(61204),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_FAILED_CONTRACT_NOT_CANCEL(61205),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_FAILED_CONTRACT_NOT_REGISTER(61206),
    SMS_HOMER_GW_VERIFICATION_INSUFFICIENT_PRIVILEGES_AND_DATA_NOT_AUTHORIZED(61207),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_OK(61300),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_FAILED(61301),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_FAILED_CONTRACT_CANCEL(61302),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_NO_DATA_FOUND(61303),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_TIMEOUT(61304),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_FAILED_CONTRACT_NOT_CANCEL(61305),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_FAILED_CONTRACT_NOT_REGISTER(61306),
    SMS_HOMER_GW_VERIFICATION_VIN_IS_MISSING_AND_DATA_NOT_AUTHORIZED(61307),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_OK(61400),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_FAILED(61401),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_FAILED_CONTRACT_CANCEL(61402),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_NO_DATA_FOUND(61403),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_TIMEOUT(61404),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_FAILED_CONTRACT_NOT_CANCEL(61405),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_FAILED_CONTRACT_NOT_REGISTER(61406),
    SMS_HOMER_GW_VERIFICATION_ACQUISITION_CHANNEL_SMARTPOS_AND_DATA_NOT_AUTHORIZED(61407),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_OK(61500),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_FAILED(61501),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_FAILED_CONTRACT_CANCEL(61502),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_NO_DATA_FOUND(61503),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_TIMEOUT(61504),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_FAILED_CONTRACT_NOT_CANCEL(61505),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_FAILED_CONTRACT_NOT_REGISTER(61506),
    SMS_HOMER_GW_VERIFICATION_CONTRACT_DOES_NOT_MATCH_CRITERIA_AND_DATA_NOT_AUTHORIZED(61507),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_OK(61600),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_FAILED(61601),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_FAILED_CONTRACT_CANCEL(61602),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_NO_DATA_FOUND(61603),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_TIMEOUT(61604),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_FAILED_CONTRACT_NOT_CANCEL(61605),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_FAILED_CONTRACT_NOT_REGISTER(61606),
    SMS_HOMER_GW_VERIFICATION_OPR_MOBILE_MISSING_AND_DATA_NOT_AUTHORIZED(61607),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_OK(61700),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_FAILED(61701),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_FAILED_CONTRACT_CANCEL(61702),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_NO_DATA_FOUND(61703),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_TIMEOUT(61704),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_FAILED_CONTRACT_NOT_CANCEL(61705),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_FAILED_CONTRACT_NOT_REGISTER(61706),
    SMS_HOMER_GW_VERIFICATION_MANDATORY_DOCUMENTS_MISSING_AND_DATA_NOT_AUTHORIZED(61707),
    /////////////////////////SMS HOMER GW END//////////////////////////////


    /////////////////////////PREFILL START///////////////////////////////////
    PREFILL_DATA_BAD_REQUEST(400400),
    PREFILL_DATA_NOT_FOUND(400404),
    PREFILL_SERVER_INTERNAL_ERROR(400500),
    /////////////////////////PREFILL END///////////////////////////////////

    /////////////////////////OFFER START///////////////////////////////////
    OFFER_DATA_BAD_REQUEST(400400),
    OFFER_DATA_NOT_FOUND(400404),
    OFFER_SERVER_INTERNAL_ERROR(400500),
    /////////////////////////OFFER END///////////////////////////////////


    /////////////////////////AL AND CONTRACT START///////////////////////////////////
    HOMER_GW_REQUEST_AL_PDF_ISNULL(22001),
    HOMER_GW_REQUEST_CONTRACT_PDF_ISNULL(22002),
    /////////////////////////AL AND CONTRACT END///////////////////////////////////


    /////////////////////////PC  START///////////////////////////////////
    RATE_RANGE_NOT_FOUND(22003),
    /////////////////////////PC  END///////////////////////////////////


    /////////////////////////1BOD START///////////////////////////////////
    APPLICATIONSTATUS_ERROR(31000),
    APPLICATION_LIMITS_ERROR(31001),
    /////////////////////////1BOD END///////////////////////////////////

    /////////////////////////////2BOD START////////////////////////////////
    CONTRACT_NOT_FIND_ERROR(80001),
    ////////////////////////////2BOD END////////////////////////////////

    PC_GENERAL_INTERNAL_SERVER_ERROR(70001),
    PC_GENERAL_UNAUTHORIZED_REQUEST_ERROR(70002);


    ResultEnum(Integer value) {
        this.value = value;
    }

    private final Integer value;

    public Integer getValue() {
        return value;
    }

    public static ResultEnum of(Integer value) {
        for (ResultEnum result : ResultEnum.values()) {
            //modify by jerry.li change == to equals
            if (result.getValue().equals(value)) {
                return result;
            }
        }
        return null;
    }
}
