/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.records;


import com.cj.jooq.jooq.tables.CustDeviceInfo;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 客户设备信息表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustDeviceInfoRecord extends UpdatableRecordImpl<CustDeviceInfoRecord> implements Record13<Integer, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -777064805;

    /**
     * Setter for <code>test.cust_device_info.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.cust_device_info.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.cust_device_info.CREATE_TIME</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.cust_device_info.CREATE_TIME</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>test.cust_device_info.CREATE_BY</code>. 创建人用户名  
     */
    public void setCreateBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.cust_device_info.CREATE_BY</code>. 创建人用户名  
     */
    public String getCreateBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.cust_device_info.UPDATE_TIME</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.cust_device_info.UPDATE_TIME</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>test.cust_device_info.UPDATE_BY</code>. 修改人用户名
     */
    public void setUpdateBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.cust_device_info.UPDATE_BY</code>. 修改人用户名
     */
    public String getUpdateBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.cust_device_info.USERNAME</code>. 用户名
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.cust_device_info.USERNAME</code>. 用户名
     */
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.cust_device_info.TERMINAL_ID</code>. 设备唯一码
     */
    public void setTerminalId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.cust_device_info.TERMINAL_ID</code>. 设备唯一码
     */
    public String getTerminalId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test.cust_device_info.PUSH_TOKEN</code>. 推送平台下发的设备唯一码
     */
    public void setPushToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.cust_device_info.PUSH_TOKEN</code>. 推送平台下发的设备唯一码
     */
    public String getPushToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>test.cust_device_info.OS_VERSION</code>. 原生系统版本
     */
    public void setOsVersion(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.cust_device_info.OS_VERSION</code>. 原生系统版本
     */
    public String getOsVersion() {
        return (String) get(8);
    }

    /**
     * Setter for <code>test.cust_device_info.BUNDLE_VERSION</code>. 客户端当前版本号，例如：1.0.1
     */
    public void setBundleVersion(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>test.cust_device_info.BUNDLE_VERSION</code>. 客户端当前版本号，例如：1.0.1
     */
    public String getBundleVersion() {
        return (String) get(9);
    }

    /**
     * Setter for <code>test.cust_device_info.FACTORY_OS_VERSION</code>. 手机厂商自定义OS，只对Android device有效)
     */
    public void setFactoryOsVersion(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>test.cust_device_info.FACTORY_OS_VERSION</code>. 手机厂商自定义OS，只对Android device有效)
     */
    public String getFactoryOsVersion() {
        return (String) get(10);
    }

    /**
     * Setter for <code>test.cust_device_info.DEVICE_MODEL</code>. 手机型号
     */
    public void setDeviceModel(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>test.cust_device_info.DEVICE_MODEL</code>. 手机型号
     */
    public String getDeviceModel() {
        return (String) get(11);
    }

    /**
     * Setter for <code>test.cust_device_info.DEVICE_TYPE</code>. 设备类型. 1:安卓  2:ios
     */
    public void setDeviceType(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>test.cust_device_info.DEVICE_TYPE</code>. 设备类型. 1:安卓  2:ios
     */
    public String getDeviceType() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, LocalDateTime, String, LocalDateTime, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustDeviceInfo.CUST_DEVICE_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return CustDeviceInfo.CUST_DEVICE_INFO.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CustDeviceInfo.CUST_DEVICE_INFO.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return CustDeviceInfo.CUST_DEVICE_INFO.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return CustDeviceInfo.CUST_DEVICE_INFO.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CustDeviceInfo.CUST_DEVICE_INFO.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CustDeviceInfo.CUST_DEVICE_INFO.TERMINAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CustDeviceInfo.CUST_DEVICE_INFO.PUSH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CustDeviceInfo.CUST_DEVICE_INFO.OS_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return CustDeviceInfo.CUST_DEVICE_INFO.BUNDLE_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CustDeviceInfo.CUST_DEVICE_INFO.FACTORY_OS_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return CustDeviceInfo.CUST_DEVICE_INFO.DEVICE_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CustDeviceInfo.CUST_DEVICE_INFO.DEVICE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getOsVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getBundleVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getFactoryOsVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getDeviceModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getDeviceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getOsVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getBundleVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getFactoryOsVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getDeviceModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getDeviceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value2(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value3(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value5(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value6(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value7(String value) {
        setTerminalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value8(String value) {
        setPushToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value9(String value) {
        setOsVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value10(String value) {
        setBundleVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value11(String value) {
        setFactoryOsVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value12(String value) {
        setDeviceModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord value13(String value) {
        setDeviceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDeviceInfoRecord values(Integer value1, LocalDateTime value2, String value3, LocalDateTime value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustDeviceInfoRecord
     */
    public CustDeviceInfoRecord() {
        super(CustDeviceInfo.CUST_DEVICE_INFO);
    }

    /**
     * Create a detached, initialised CustDeviceInfoRecord
     */
    public CustDeviceInfoRecord(Integer id, LocalDateTime createTime, String createBy, LocalDateTime updateTime, String updateBy, String username, String terminalId, String pushToken, String osVersion, String bundleVersion, String factoryOsVersion, String deviceModel, String deviceType) {
        super(CustDeviceInfo.CUST_DEVICE_INFO);

        set(0, id);
        set(1, createTime);
        set(2, createBy);
        set(3, updateTime);
        set(4, updateBy);
        set(5, username);
        set(6, terminalId);
        set(7, pushToken);
        set(8, osVersion);
        set(9, bundleVersion);
        set(10, factoryOsVersion);
        set(11, deviceModel);
        set(12, deviceType);
    }
}
