/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.records;


import com.cj.jooq.jooq.tables.CustDevicePushLog;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 设备推送日志表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustDevicePushLogRecord extends UpdatableRecordImpl<CustDevicePushLogRecord> implements Record14<Integer, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String, Integer, String, Integer, String, String> {

    private static final long serialVersionUID = 1177579990;

    /**
     * Setter for <code>test.cust_device_push_log.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>test.cust_device_push_log.CREATE_TIME</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.CREATE_TIME</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>test.cust_device_push_log.CREATE_BY</code>. 创建人用户名
     */
    public void setCreateBy(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.CREATE_BY</code>. 创建人用户名
     */
    public String getCreateBy() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.cust_device_push_log.UPDATE_TIME</code>.
     */
    public void setUpdateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.UPDATE_TIME</code>.
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>test.cust_device_push_log.UPDATE_BY</code>. 修改人用户名
     */
    public void setUpdateBy(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.UPDATE_BY</code>. 修改人用户名
     */
    public LocalDateTime getUpdateBy() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>test.cust_device_push_log.USERNAME</code>. 用户名
     */
    public void setUsername(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.USERNAME</code>. 用户名
     */
    public String getUsername() {
        return (String) get(5);
    }

    /**
     * Setter for <code>test.cust_device_push_log.TERMINAL_ID</code>. 设备唯一码
     */
    public void setTerminalId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.TERMINAL_ID</code>. 设备唯一码
     */
    public String getTerminalId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>test.cust_device_push_log.PUSH_TOKEN</code>. 推送平台下发的设备唯一码
     */
    public void setPushToken(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.PUSH_TOKEN</code>. 推送平台下发的设备唯一码
     */
    public String getPushToken() {
        return (String) get(7);
    }

    /**
     * Setter for <code>test.cust_device_push_log.DEVICE_TYPE</code>. 设备类型. 1:安卓  2:ios
     */
    public void setDeviceType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.DEVICE_TYPE</code>. 设备类型. 1:安卓  2:ios
     */
    public String getDeviceType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>test.cust_device_push_log.SEQ</code>. 异步服务中可以通过该字段找到server端返回的对应应答包
     */
    public void setSeq(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.SEQ</code>. 异步服务中可以通过该字段找到server端返回的对应应答包
     */
    public Integer getSeq() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>test.cust_device_push_log.ENVIRONMENT</code>. 用户指定推送环境.product:生产环境, dev:开发环境
     */
    public void setEnvironment(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.ENVIRONMENT</code>. 用户指定推送环境.product:生产环境, dev:开发环境
     */
    public String getEnvironment() {
        return (String) get(10);
    }

    /**
     * Setter for <code>test.cust_device_push_log.RET_CODE</code>. 错误码
     */
    public void setRetCode(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.RET_CODE</code>. 错误码
     */
    public Integer getRetCode() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>test.cust_device_push_log.PUSH_ID</code>. 推送id
     */
    public void setPushId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.PUSH_ID</code>. 推送id
     */
    public String getPushId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>test.cust_device_push_log.MESSAGE</code>. 日志内容的描述
     */
    public void setMessage(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>test.cust_device_push_log.MESSAGE</code>. 日志内容的描述
     */
    public String getMessage() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String, Integer, String, Integer, String, String> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Integer, LocalDateTime, String, LocalDateTime, LocalDateTime, String, String, String, String, Integer, String, Integer, String, String> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.TERMINAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.PUSH_TOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.DEVICE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.SEQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.ENVIRONMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.RET_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.PUSH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return CustDevicePushLog.CUST_DEVICE_PUSH_LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getDeviceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getEnvironment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getRetCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getPushId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTerminalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getPushToken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getDeviceType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSeq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getEnvironment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getRetCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getPushId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value2(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value3(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value4(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value5(LocalDateTime value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value6(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value7(String value) {
        setTerminalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value8(String value) {
        setPushToken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value9(String value) {
        setDeviceType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value10(Integer value) {
        setSeq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value11(String value) {
        setEnvironment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value12(Integer value) {
        setRetCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value13(String value) {
        setPushId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord value14(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustDevicePushLogRecord values(Integer value1, LocalDateTime value2, String value3, LocalDateTime value4, LocalDateTime value5, String value6, String value7, String value8, String value9, Integer value10, String value11, Integer value12, String value13, String value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustDevicePushLogRecord
     */
    public CustDevicePushLogRecord() {
        super(CustDevicePushLog.CUST_DEVICE_PUSH_LOG);
    }

    /**
     * Create a detached, initialised CustDevicePushLogRecord
     */
    public CustDevicePushLogRecord(Integer id, LocalDateTime createTime, String createBy, LocalDateTime updateTime, LocalDateTime updateBy, String username, String terminalId, String pushToken, String deviceType, Integer seq, String environment, Integer retCode, String pushId, String message) {
        super(CustDevicePushLog.CUST_DEVICE_PUSH_LOG);

        set(0, id);
        set(1, createTime);
        set(2, createBy);
        set(3, updateTime);
        set(4, updateBy);
        set(5, username);
        set(6, terminalId);
        set(7, pushToken);
        set(8, deviceType);
        set(9, seq);
        set(10, environment);
        set(11, retCode);
        set(12, pushId);
        set(13, message);
    }
}
