/*
 * This file is generated by jOOQ.
*/
package com.cj.jooq.jooq.tables.records;


import com.cj.jooq.jooq.tables.UUser;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UUserRecord extends UpdatableRecordImpl<UUserRecord> implements Record13<String, String, String, String, String, LocalDateTime, Long, String, Integer, LocalDateTime, String, LocalDateTime, String> {

    private static final long serialVersionUID = 1418101151;

    /**
     * Setter for <code>test.u_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>test.u_user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>test.u_user.userName</code>. 用户登录名
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>test.u_user.userName</code>. 用户登录名
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>test.u_user.realname</code>. 用户真实姓名
     */
    public void setRealname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>test.u_user.realname</code>. 用户真实姓名
     */
    public String getRealname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>test.u_user.email</code>. 邮箱|登录帐号
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>test.u_user.email</code>. 邮箱|登录帐号
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>test.u_user.password</code>. 密码
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>test.u_user.password</code>. 密码
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>test.u_user.last_login_time</code>. 最后登录时间
     */
    public void setLastLoginTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>test.u_user.last_login_time</code>. 最后登录时间
     */
    public LocalDateTime getLastLoginTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>test.u_user.status</code>. 1:有效，0:禁止登录
     */
    public void setStatus(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>test.u_user.status</code>. 1:有效，0:禁止登录
     */
    public Long getStatus() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>test.u_user.salt</code>. 加密密码的盐
     */
    public void setSalt(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>test.u_user.salt</code>. 加密密码的盐
     */
    public String getSalt() {
        return (String) get(7);
    }

    /**
     * Setter for <code>test.u_user.age</code>.
     */
    public void setAge(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>test.u_user.age</code>.
     */
    public Integer getAge() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>test.u_user.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>test.u_user.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>test.u_user.create_by</code>. 创建人id
     */
    public void setCreateBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>test.u_user.create_by</code>. 创建人id
     */
    public String getCreateBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>test.u_user.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>test.u_user.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>test.u_user.update_by</code>. 修改人id
     */
    public void setUpdateBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>test.u_user.update_by</code>. 修改人id
     */
    public String getUpdateBy() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, LocalDateTime, Long, String, Integer, LocalDateTime, String, LocalDateTime, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<String, String, String, String, String, LocalDateTime, Long, String, Integer, LocalDateTime, String, LocalDateTime, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UUser.U_USER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return UUser.U_USER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UUser.U_USER.REALNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UUser.U_USER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UUser.U_USER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return UUser.U_USER.LAST_LOGIN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return UUser.U_USER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UUser.U_USER.SALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return UUser.U_USER.AGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field10() {
        return UUser.U_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return UUser.U_USER.CREATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field12() {
        return UUser.U_USER.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return UUser.U_USER.UPDATE_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getRealname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getLastLoginTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getSalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getAge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUpdateBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value3(String value) {
        setRealname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value5(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value6(LocalDateTime value) {
        setLastLoginTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value7(Long value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value8(String value) {
        setSalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value9(Integer value) {
        setAge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value11(String value) {
        setCreateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value12(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord value13(String value) {
        setUpdateBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUserRecord values(String value1, String value2, String value3, String value4, String value5, LocalDateTime value6, Long value7, String value8, Integer value9, LocalDateTime value10, String value11, LocalDateTime value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UUserRecord
     */
    public UUserRecord() {
        super(UUser.U_USER);
    }

    /**
     * Create a detached, initialised UUserRecord
     */
    public UUserRecord(String id, String username, String realname, String email, String password, LocalDateTime lastLoginTime, Long status, String salt, Integer age, LocalDateTime createTime, String createBy, LocalDateTime updateTime, String updateBy) {
        super(UUser.U_USER);

        set(0, id);
        set(1, username);
        set(2, realname);
        set(3, email);
        set(4, password);
        set(5, lastLoginTime);
        set(6, status);
        set(7, salt);
        set(8, age);
        set(9, createTime);
        set(10, createBy);
        set(11, updateTime);
        set(12, updateBy);
    }
}
